version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: dim_product
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: fact_order_items
    columns:
      - name: order_item_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_id

      - name: product_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_product')
                field: product_id

